# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Florian Wagner 
# Description of the Site
description: “Attack is the secret of defense; defense is the planning of an attack.” ― Sun Tzu 

# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://cdn.pixabay.com/photo/2018/04/22/22/57/hacker-3342696_1280.jpg 
#heroimage: https://cdn.pixabay.com/photo/2017/01/01/14/39/hacker-1944688_1280.jpg 

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: mail@florianwagner.me 
#facebook_username: 
twitter_username: florianwagnerme
#instagram_username: thedevslot
linkedin_username: florianwagnerdotme
github_username:  florianwagnerdotme
#youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Florian Wagner
# URL for the Image of the Author
author-image: https://florianwagner.me/assets/images/about/profilePhoto.jpg
# 60 Words About the Author
author-about: Dear friend, my name is Florian Wagner. As a solopreneur I founded my own Cyber Security Company, was Project Security Manager and am now working as an Ethical Hacker. My experiences range from penetration testing of government applications over managing the security of big projects like the German Corona Warn App (CWA) and its European Federation Gateway Service (EFGS) to partaking in the IDM security standardization of projects within the GSMA. Currently I am on the road to fine tune my hacking skills by developing own projects, working together with the hacker community and my team at work and doing CTFs as well as bug bounties.  Let us gladly connect and have a chat! 👇👇👇 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://me.linkedin.com/in/florianwagnerdotme

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
